project:
  name: joustokontti
  regions:
    - eu-central-1
  shorten_stack_name: true
tests:
  default:
    template: ./target/ecs.yml
    parameters:
      DockerImageUri: <paste-real-docker-image-uri-here>
