# docker build --rm -t joustokontti:dev -f Dockerfile.dev .
# docker run -it --rm -p 10000:10000 -v "$(pwd)":/usr/local/src/joustokontti --name joustokontti-dev joustokontti:dev
# docker run -it --rm -p 10000:10000 -v `pwd`:/usr/local/src/joustokontti --name joustokontti-dev joustokontti:dev
# Windows command line
# docker run -it --rm -p 10000:10000 -v %cd%:/usr/local/src/joustokontti --name joustokontti-dev joustokontti:dev
# Windows PowerShell
# docker run -it --rm -p 10000:10000 -v ${PWD}:/usr/local/src/joustokontti --name joustokontti-dev joustokontti:dev

FROM clojure:latest

WORKDIR /usr/local/src/joustokontti

ENTRYPOINT ["bash"]
